FROM golang:1.13 as builder
WORKDIR /app
COPY invoke.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -v -o server

FROM ghcr.io/dbt-labs/dbt-bigquery:1.3.latest
USER root
WORKDIR /demo
COPY --from=builder /app/server ./
COPY run.sh ./
COPY . ./

ENTRYPOINT "./server"